name: virotour
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  build_runner: '>=1.6.2 <3.0.0'
  build_web_compilers: '>=2.12.0 <4.0.0'

flutter:
  uses-material-design: true

  assets:
    - assets/
